- name: Setup Quay and Clair Containers
  hosts: quay
  gather_facts: no
  any_errors_fatal: yes
  tags:
  - quay
  pre_tasks:
  - when: is_quay | default(false) | bool
    block:
    - name: Get Quay User UID
      shell: "getent passwd {{ quay_runtime_user }} | cut -d ':' -f 3 || false"
      changed_when: false
      register: quay_runtime_uid_out
    - name: Setup user for Quay
      when: "quay_runtime_uid_out.stdout | default('') == ''"
      user:
        name: "{{ quay_runtime_user }}"
        system: yes
        home: /dev/null
        shell: /bin/false
        create_home: no

  - when: is_clair | default(false) | bool
    block:
    - name: Get Clair User UID
      shell: "getent passwd {{ clair_runtime_user }} | cut -d ':' -f 3 || false"
      changed_when: false
      register: clair_runtime_uid_out
    - name: Setup user for Clair
      when: "clair_runtime_uid_out.stdout | default('') == ''"
      user:
        name: "{{ clair_runtime_user }}"
        system: yes
        home: /dev/null
        shell: /bin/false
        create_home: no
  roles:
  - quay
