- name: Set container_manage_cgroup flag on and keep it persistent across reboots
  when: ansible_facts['distribution'] == "Red Hat Enterprise Linux"
  ansible.posix.seboolean:
    name: container_manage_cgroup
    state: yes
    persistent: yes
