
- when: "inventory_hostname == quay_setup_client"
  delegate_to: "{{ quay_setup_client }}"
  run_once: yes
  become: true
  block:
  - name: "Setup Quay Postgres Database"
    postgresql_db:
      login_host: "{{ quay_db_hostname }}"
      port: "{{ quay_db_port }}"
      login_user: "{{ quay_db_admin_username }}"
      login_password: "{{ quay_db_admin_password }}"
      name: "{{ quay_db_dbname }}"
      ssl_mode: "{{ quay_db_sslmode | default(omit) }}"
      ca_cert: "{{ quay_db_ca_file | default(omit) }}"

  - name: "Setup Quay Postgres User"
    when: "quay_db_admin_username | default('postgres') != quay_db_username"
    postgresql_user:
      login_host: "{{ quay_db_hostname }}"
      port: "{{ quay_db_port }}"
      login_user: "{{ quay_db_admin_username | default('postgres') }}"
      login_password: "{{ quay_db_admin_password }}"
      name: "{{ quay_db_username.split('@') | first }}"
      db: "{{ quay_db_dbname }}"
      priv: ALL
      password: "{{ quay_db_password }}"
      ssl_mode: "{{ quay_db_sslmode | default(omit) }}"
      ca_cert: "{{ quay_db_ca_file | default(omit) }}"

  - name: "Setup Quay Postgres pg_trgm Extension"
    postgresql_ext:
      login_host: "{{ quay_db_hostname }}"
      port: "{{ quay_db_port | default(5432) }}"
      login_user: "{{ quay_db_admin_username }}"
      login_password: "{{ quay_db_admin_password }}"
      db: "{{ quay_db_dbname }}"
      ssl_mode: "{{ quay_db_sslmode | default(omit) }}"
      ca_cert: "{{ quay_db_ca_file | default(omit) }}"
      name: pg_trgm

  - name: "Setup Clair Postgres Database"
    postgresql_db:
      login_host: "{{ clair_db_hostname }}"
      port: "{{ clair_db_port }}"
      login_user: "{{ clair_db_admin_username }}"
      login_password: "{{ clair_db_admin_password }}"
      name: "{{ clair_db_dbname }}"
      ssl_mode: "{{ clair_db_sslmode | default(omit) }}"
      ca_cert: "{{ clair_db_ca_file | default(omit) }}"

  - name: "Setup Clair Postgres User"
    when:
      - "clair_db_admin_username | default('postgres') != clair_db_username"
    postgresql_user:
      login_host: "{{ clair_db_hostname }}"
      port: "{{ clair_db_port }}"
      login_user: "{{ clair_db_admin_username | default('postgres')}}"
      login_password: "{{ clair_db_admin_password }}"
      name: "{{ clair_db_username.split('@') | first }}"
      db: "{{ clair_db_dbname }}"
      priv: ALL
      password: "{{ clair_db_password }}"
      ssl_mode: "{{ clair_db_sslmode | default(omit) }}"
      ca_cert: "{{ clair_db_ca_file | default(omit) }}"

  - name: "Setup Clair Postgres pg_trgm Extension"
    postgresql_ext:
      login_host: "{{ clair_db_hostname }}"
      port: "{{ clair_db_port }}"
      login_user: "{{ clair_db_admin_username }}"
      login_password: "{{ clair_db_admin_password }}"
      db: "{{ clair_db_dbname }}"
      ssl_mode: "{{ clair_db_sslmode | default(omit) }}"
      ca_cert: "{{ clair_db_ca_file | default(omit) }}"
      name: uuid-ossp
      state: present





